### ISSUE TITLE
Not finding any bookmarks

### ISSUE THREAD

**Issue by Lawdawg** [nikipore/alfred-firefoxbookmarks#4]
I installed this and when I type "ff" is says below, "Firefox Bookmarks - Search Firefox Bookmarks", but it won't bring anything up when I search. For instance, I bookmarked Google.com and name the bookmark, "Google", and when I type "ff Google" into Alfred, it doesn't bring any results up from my Firefox bookmarks.

What might be causing this?

**Comment by divarre** [comment]
Hi,
The same thing was happening to me, so I checked and that's because my Firefox profile folder is named `xxxxxx.default-1234567890123` and not just `xxxxxx.default`.

To fix this, I just changed the Script in Alfred (double-click the *Script Filter* item in *Firefox Bookmarks*) from:

`PROFILE="~/Library/Application Support/Firefox/Profiles/*.default"
python bookmarks.py "${PROFILE}" "{query}"`

to

`PROFILE="~/Library/Application Support/Firefox/Profiles/*.default-*"
python bookmarks.py "${PROFILE}" "{query}"`

**Comment by will-sippl** [comment]
@divarre 's solution worked perfectly for me too. Thanks!

**Comment by Lawdawg** [comment]
Fixed it!
Mine was originally:
   PROFILE="~/Library/Application Support/Firefox/Profiles/*.default.*" python bookmarks.py "${PROFILE}" "{query}"

So I changed it to:
   PROFILE="~/Library/Application Support/Firefox/Profiles/*.default*" python bookmarks.py "${PROFILE}" "{query}"

And now it works! Thanks!
